using namespace std;

#include <assert.h>
#include <cstdio>
#include <cstdarg> 
#include <fstream>
#include <iostream>
#include <sstream>
#include <utility>
#include <limits>
#include <cstring>
#include <cmath>
#include <chrono>
#include <random>
#include <algorithm>
#include <list>
#include <stack>
#include <bitset>
#include <queue>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <numeric>
#include <dirent.h>
#include <sys/types.h>
#include "lib/parallel_hashmap/phmap.h"
#include "lib/pop.h"
#include "helper.cc"
using phmap::flat_hash_map;
using phmap::flat_hash_set;
